### ISSUE TITLE
Clean UP & Dockerization eos1amr

### ISSUE THREAD

**Issue by GemmaTuron** [ersilia-os/eos1amr#1]
Please check that the model is working and refactor it model to the latest eos-template structure.
The workflows have already been updated, you can start by checking if the Actions have run successfully or changes need to be made

**Comment by GemmaTuron** [comment]
@samuelmaina I am moving the conversation here to keep the issues in one single conversation.
The current model is run from the file `main.py `inside the grover folder, as stated in the `service.py` file:
`lines = ["python {0}/grover/main.py {1} {2}".format(self.framework_dir, data_file, pred_file)] `

This main.py should be moved out of the grover folder, into the code folder, to maintain the structure of the eos-template. The checkpoints should go to the checkpoints directory and the bash file run.sh should be created. the service.py should be edited to point to that run.sh file. Make sure all paths are edited to the correct directories

First, make those edits and then we will investigate about the retraining issue.
You can push your changes to your fork of the model (without opening a PR) so that we can see them.
I hope this is helpful, try to do the minimum changes and get the model to work in the new template then we'll think about optimising it.

**Comment by samuelmaina** [comment]
@GemmaTuron , I tried to create one function from the main.py of the grove folder  and calling the it in the main.py of the code folder  but I had errors with the grover imports in the grover's main.py.  I couldn't find a work around. 
The  checkpoints are autogenerated by the model   in the framework folder and in the grover/exampledata folder, I need to dig deeper to control this behavior.
I have confirmed that the run.sh is in the correct folder. 
I will push my update so you can see my changed in the fork.

**Comment by GemmaTuron** [comment]
Ok, yes please push to your fork and we'll have a look.
Also, the imports failing must be due to how we direct the paths, what error exactly did you find?

**Comment by samuelmaina** [comment]
@GemmaTuron , I am getting EmptyOutputError but I can generate output file in the run.sh .I have pushed the code, you can have a look.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

The EmptyOutputError is basically just telling you that the model has failed, but to really understand the error I need to see the full log. Please provide that and we can try to see what is failing together. I'd appreciate if you have a look first and pinpoint the useful lines of information to identify the error.

**Comment by samuelmaina** [comment]
@GemmaTuron ,  I have looked into the logs  and I can see any error with the model or ersilia. The model print statements are displayed in the logs  which shows the model is being called successfully.
Here are the full logs. 
[eos1amr_cli_fetch.log](https://github.com/ersilia-os/eos1amr/files/11917752/eos1amr_cli_fetch.log)

**Comment by GemmaTuron** [comment]
@samuelmaina 
Did you change any installation requirements? I am getting this error:

```
Detailed error:
Model API eos1amr:run did not produce an outputWARNING:root:No normalization for BCUT2D_MWHI
WARNING:root:No normalization for BCUT2D_MWLOW
WARNING:root:No normalization for BCUT2D_CHGHI
WARNING:root:No normalization for BCUT2D_CHGLO
WARNING:root:No normalization for BCUT2D_LOGPHI
WARNING:root:No normalization for BCUT2D_LOGPLOW
WARNING:root:No normalization for BCUT2D_MRHI
WARNING:root:No normalization for BCUT2D_MRLOW
[WARNING] Horovod cannot be imported; multi-GPU training is unsupported
```
It seems that you are trying to install something on GPU format

**Comment by GemmaTuron** [comment]
I have also noticed that the workflows were not there, please if you find that let me know because it might have slipped through. I am updating them now.

**Comment by samuelmaina** [comment]
Okay I will be reporting on the  workflows. I have only changed the rkdit version from `RUN conda install -c conda-forge rdkit=2021.03.4` to `RUN pip install rdkit-pypi`  in which  ` rdkit-pypi` will give version 2021.03 . 
I  was getting the warning when running the  run.sh in the model env  and it was producing an output.

**Comment by samuelmaina** [comment]
I will be updating you if I get the workflows missing. I normally add them manually.

**Comment by samuelmaina** [comment]
Hi @GemmaTuron ,
I have managed to fetch and predict with eml dataset. The issue was with the difference in temp output files in the two services. I have put two different snippets in the PR.
 - [eos1amr_cli_fetch.log](https://github.com/ersilia-os/eos1amr/files/11960815/eos1amr_codesp_fetch.log)
 - [eos1amr_eml_cli_pred.csv](https://github.com/ersilia-os/eos1amr/files/11960816/eos1amr_eml_cli_pred.csv)

**Comment by GemmaTuron** [comment]
Can you explain what you mean by the difference in temp output files?

**Comment by samuelmaina** [comment]
@GemmaTuron , The main issue was with sharing of temp files between the model and ersilia. The new service.py uses run.log  and _output.csv which were identifical to what the model had created and used. The model override what ersilia had created hence the empty output error.
```
#The standard service.py
class Model(object):
    def __init__(self):
        self.DATA_FILE = "_data.csv"
        self.OUTPUT_FILE = "_output.csv"
        self.RUN_FILE = "_run.sh"
        self.LOG_FILE = "run.log"
```
```
# The service.py that the model was using before refactoring.
class Model(object):
   def __init__(self):
          self.DATA_FILE = "_data.csv"
          self.PRED_FILE = "_pred.csv"
          self.RUN_FILE = "_run.sh"
          self.LOG_FILE = "_run.log"
```
